### ISSUE TITLE
markdown.lua:974: empty loop in rule 'Blocks'

### ISSUE THREAD

**Issue by daurnimator** [jgm/lunamark#11]
```
$ lunamark
/usr/bin/lua5.1: /usr/share/lua/5.1/lunamark/reader/markdown.lua:974: empty loop in rule 'Blocks'
stack traceback:
        [C]: in function 'Ct'
        /usr/share/lua/5.1/lunamark/reader/markdown.lua:974: in function 'new'
        ...r/lib/luarocks/rocks-5.1/lunamark/0.3-1/bin/lunamark:399: in main chunk
        [C]: ?
```

I have lpeg 0.12.1 and lunamark 0.3

**Comment by jan-dx** [comment]
I am getting the same error with lpeg 0.12.2-1 and lunamark 0.3-1. Until it is confirmed and fixed by developers, you may want to apply this change; in `lunamark/reader/markdown.lua` file, change line 893 from
```
(Blank^0 / function() return writer.interblocksep end * Block)^0 *
```
to
```
(Blank^1 / function() return writer.interblocksep end * Block)^0
```

**Comment by jgm** [comment]
I think that change will have the result that block elements
must be separated by blank lines, which isn't generally true
in Markdown.

+++ Nazım Can Bedir [Sep 22 15 17:11 ]:

**Comment by jan-dx** [comment]
The cause of current error is strictness of new LPeg version (for author's comment, please see [lua-l message]). Until there is a fix for this, LPeg 0.10 is working with current implementation. LPeg 0.11 is not option here, because it throws "pattern too large" error.

[lua-l message]: http://lua-users.org/lists/lua-l/2013-06/msg00086.html

**Comment by Guard13007** [comment]
So I just stumbled across this library...and this bug is still there.

Is this going to be fixed? Or what? I wish I knew enough of what I'm doing to fix it myself. I tried the hacky suggestion above, and now I just get the following:

```
markdown.lua:124: parse_blocks failed on:
This is a test of Ma
```

The source of that btw is:

```
This is a test of MarkDown!
=====================

It *should* be working?

[here's](http://google.com) a link to google
```

**Comment by jgm** [comment]
I don't really actively maintain this any more.  But try this:
``` diff
diff --git a/lunamark/reader/markdown.lua b/lunamark/reader/markdown.lua
index d4331ea..ca3fd8c 100644
--- a/lunamark/reader/markdown.lua
+++ b/lunamark/reader/markdown.lua
@@ -890,7 +890,7 @@ function M.new(writer, options)
 
       Blocks                = Blank^0 *
                               Block^-1 *
-                              (Blank^0 / function() return writer.interblocksep end * Block)^0 *
+                              (Blank^0 / function() return writer.interblocksep end * Block)^1 *
                               Blank^0 *
                               eof,
```

**Comment by jgm** [comment]
If this works (and tests pass), let me know and I can push it.
(I only have lua 5.2 installed right now, and lunamark doesn't build with that.)

**Comment by daurnimator** [comment]
> If this works (and tests pass), let me know and I can push it.

It doesn't work.

> (I only have lua 5.2 installed right now, and lunamark doesn't build with that.)

I might do some work tonight to update it.

**Comment by jgm** [comment]
I understand now, thanks.

**Comment by daurnimator** [comment]
> A hackish solution would be to remove the initial less from openelt_block and make
> This would probably require some other adjustments -- again, I can't test.

Indeed. `parse_matched_tags` expects the Cmt to begin with a '<' 
I tried with this patch:
```diff
diff --git a/lunamark/reader/markdown.lua b/lunamark/reader/markdown.lua
index 07d12b0..17f573c 100644
--- a/lunamark/reader/markdown.lua
+++ b/lunamark/reader/markdown.lua
@@ -536,11 +536,11 @@ function M.new(writer, options)
   end
 
   local function parse_matched_tags(s,pos)
-    local t = utf8_lower(lpegmatch(less * C(keyword),s,pos))
-    return lpegmatch(in_matched(t),s,pos)
+    local t = utf8_lower(lpegmatch(C(keyword),s,pos))
+    return lpegmatch("<"..in_matched(t),s,pos)
   end
 
-  local in_matched_block_tags = Cmt(#openelt_block, parse_matched_tags)
+  local in_matched_block_tags = less * Cmt(#openelt_block, parse_matched_tags)
 
   local displayhtml = htmlcomment
                     + emptyelt_block
```

Which I think works..... but other issues come up during the tests. e.g. some things seem to have gained a `<p>` wrapper

> By the way, the problem with 5.2 is that slnunicode doesn't build with 5.2. (And maybe it's no longer needed with 5.2.)

Fixed that in my PR #14

**Comment by daurnimator** [comment]
> Which I think works..... but other issues come up during the tests. e.g. some things seem to have gained a <p> wrapper

Fixed the issues. Added to PR #14.
